import type { Metadata } from 'next'
import { buildPageMetadata, buildBreadcrumbJsonLd, BASE_URL } from '@/lib/seo'
import { Link } from '@/i18n/navigation'

const content = {
  'en-US': {
    title: 'Terms of Service',
    lastUpdated: 'Last updated: March 1, 2026',
    intro:
      'These Terms of Service ("Terms") govern your access to and use of the cloud-based customs and foreign trade operations platform ("the Service") provided by Aduvanta Technologies, S.A.P.I. de C.V. ("Aduvanta", "we", "us", or "our"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, you may not use the Service.',
    sections: [
      {
        heading: '1. Definitions',
        body: '"Customer" refers to the legal entity or individual that registers for the Service and enters into a subscription agreement with Aduvanta.\n\n"Organization" refers to the tenant workspace created within the Service, representing a company, customs brokerage, or business unit.\n\n"User" refers to any individual authorized by the Customer to access the Service under the Customer\'s Organization.\n\n"Subscription" refers to the paid plan selected by the Customer that determines service tier, feature access, and usage limits.\n\n"Customer Data" refers to all data, files, documents, records, and information uploaded, entered, or generated by the Customer or its Users within the Service.\n\n"Platform" refers to the Aduvanta web application, APIs, and all related infrastructure and services.',
      },
      {
        heading: '2. Account Registration and Organization Setup',
        body: 'To use the Service, you must create an account and set up an Organization. You agree to provide accurate, complete, and current information during registration and to keep your account information updated.\n\nEach Organization must designate at least one administrator who is responsible for managing Users, roles, permissions, and Organization settings.\n\nYou are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account or Organization. You must notify Aduvanta immediately of any unauthorized use of your account.\n\nAduvanta reserves the right to refuse registration or to suspend accounts that violate these Terms or that provide false or misleading information.',
      },
      {
        heading: '3. Subscription and Billing',
        body: 'The Service is offered on a subscription basis. All prices are quoted and payable in Mexican Pesos (MXN) plus applicable taxes (IVA).\n\nNew Customers are eligible for a 14-day free trial with full access to the selected plan features. No payment information is required to start the trial. At the end of the trial period, the Customer must select a paid plan to continue using the Service.\n\nSubscriptions are billed monthly or annually, as selected by the Customer. Annual subscriptions receive a discount as published on our pricing page. Payment is due at the beginning of each billing cycle.\n\nAduvanta will issue a valid CFDI (Comprobante Fiscal Digital por Internet) for each payment received.\n\nIf payment is not received within 15 calendar days of the due date, Aduvanta reserves the right to suspend access to the Service until payment is received. Repeated payment failures may result in account termination.\n\nAduvanta may adjust pricing with at least 30 days prior written notice. Price changes will take effect at the start of the next billing cycle.',
      },
      {
        heading: '4. Acceptable Use',
        body: 'You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not:\n\n• Use the Service to violate any applicable law or regulation, including Mexican customs, tax, and trade laws.\n• Attempt to gain unauthorized access to any part of the Service, other accounts, or systems connected to the Service.\n• Interfere with or disrupt the integrity or performance of the Service or its infrastructure.\n• Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Service.\n• Use the Service to transmit malware, viruses, or any harmful code.\n• Share account credentials or allow unauthorized third parties to access the Service through your account.\n• Use automated tools (bots, scrapers) to access the Service without prior written authorization from Aduvanta.\n• Upload or transmit content that infringes intellectual property rights of third parties.\n\nAduvanta reserves the right to suspend or terminate access for any Customer or User that violates these acceptable use provisions.',
      },
      {
        heading: '5. Customer Data Ownership',
        body: 'The Customer retains all ownership rights to Customer Data. Aduvanta does not acquire any ownership interest in Customer Data by virtue of providing the Service.\n\nAduvanta acts as a data processor with respect to Customer Data. We process Customer Data solely as necessary to provide the Service and as instructed by the Customer, in compliance with our Privacy Policy and applicable data protection laws.\n\nAduvanta will not access, use, or disclose Customer Data except: (a) as necessary to provide and maintain the Service; (b) to comply with applicable law or a valid legal order; (c) as expressly authorized by the Customer; or (d) to protect the security and integrity of the Service.\n\nUpon termination of the subscription, the Customer may request an export of their Customer Data within 30 calendar days. After this period, Aduvanta may permanently delete Customer Data, except where retention is required by law.',
      },
      {
        heading: '6. Intellectual Property',
        body: 'The Service, including its software, architecture, design, user interface, documentation, APIs, trademarks, and all related intellectual property, is and remains the exclusive property of Aduvanta Technologies, S.A.P.I. de C.V.\n\nThese Terms grant the Customer a limited, non-exclusive, non-transferable, revocable license to access and use the Service during the active subscription period, solely for the Customer\'s internal business operations.\n\nNo rights are granted to copy, modify, distribute, sell, or create derivative works based on the Service or any part thereof.\n\nFeedback, suggestions, or feature requests submitted by Customers or Users may be used by Aduvanta without any obligation of compensation or attribution.',
      },
      {
        heading: '7. Service Availability and SLA',
        body: 'Aduvanta commits to a target availability of 99.9% for the Service, measured monthly, excluding scheduled maintenance windows.\n\nScheduled maintenance will be communicated at least 48 hours in advance and will be performed during low-usage periods whenever possible.\n\nIn the event of unscheduled downtime exceeding the 99.9% target in a given calendar month, Customers on annual plans may request service credits in accordance with the applicable Service Level Agreement (SLA) published on our website.\n\nAduvanta is not responsible for downtime caused by: (a) factors outside our reasonable control, including force majeure events; (b) the Customer\'s equipment, software, or network connections; (c) third-party services or APIs not operated by Aduvanta; or (d) Customer actions that violate these Terms.',
      },
      {
        heading: '8. Limitation of Liability',
        body: 'To the maximum extent permitted by applicable law:\n\nAduvanta shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, revenue, data, business opportunities, or goodwill, arising out of or in connection with the use of or inability to use the Service.\n\nAduvanta\'s total aggregate liability for any claims arising out of or related to these Terms or the Service shall not exceed the total amount paid by the Customer to Aduvanta during the 12-month period immediately preceding the event giving rise to the claim.\n\nThe Service is provided for business operational support. Aduvanta does not guarantee that the use of the Service will ensure compliance with any regulatory requirements. The Customer remains solely responsible for verifying the accuracy of customs declarations, tariff classifications, and all regulatory filings.\n\nThese limitations apply regardless of the legal theory upon which the claim is based, whether in contract, tort, negligence, strict liability, or otherwise.',
      },
      {
        heading: '9. Termination',
        body: 'The Customer may terminate the subscription at any time by providing written notice through the platform or via email to legal@aduvanta.com. Termination will take effect at the end of the current billing cycle. No refunds will be issued for partial billing periods.\n\nAduvanta may terminate or suspend the Customer\'s access to the Service immediately, without prior notice, if: (a) the Customer materially breaches these Terms and fails to cure the breach within 15 calendar days of written notice; (b) the Customer engages in illegal activity using the Service; (c) the Customer fails to pay fees for more than 30 calendar days past due; or (d) Aduvanta is required to do so by law.\n\nUpon termination: (a) all rights granted to the Customer under these Terms will cease immediately; (b) the Customer must cease all use of the Service; (c) the Customer may request a data export within 30 calendar days as described in Section 5; and (d) outstanding payment obligations survive termination.',
      },
      {
        heading: '10. Governing Law and Jurisdiction',
        body: 'These Terms shall be governed by and construed in accordance with the laws of the United Mexican States (Mexico).\n\nAny dispute, controversy, or claim arising out of or relating to these Terms or the Service shall be submitted to the exclusive jurisdiction of the competent courts located in Monterrey, Nuevo Leon, Mexico.\n\nThe parties agree to waive any other jurisdiction that may correspond to them by reason of their present or future domicile or for any other reason.',
      },
      {
        heading: '11. General Provisions',
        body: 'Entire Agreement: These Terms, together with the Privacy Policy and any applicable Service Level Agreement, constitute the entire agreement between the Customer and Aduvanta regarding the Service.\n\nSeverability: If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.\n\nWaiver: The failure of Aduvanta to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.\n\nAssignment: The Customer may not assign or transfer these Terms without the prior written consent of Aduvanta. Aduvanta may assign these Terms in connection with a merger, acquisition, or sale of all or substantially all of its assets.\n\nNotices: Notices from Aduvanta to the Customer will be sent to the email address associated with the Customer\'s account. Notices from the Customer to Aduvanta must be sent to legal@aduvanta.com.',
      },
      {
        heading: '12. Contact Information',
        body: 'For questions about these Terms of Service, please contact us at:\n\nAduvanta Technologies, S.A.P.I. de C.V.\nEmail: legal@aduvanta.com\nWebsite: https://aduvanta.com',
      },
    ],
  },
  'es-MX': {
    title: 'Terminos y Condiciones',
    lastUpdated: 'Ultima actualizacion: 1 de marzo de 2026',
    intro:
      'Los presentes Terminos y Condiciones ("Terminos") regulan el acceso y uso de la plataforma de operaciones aduanales y comercio exterior en la nube ("el Servicio") proporcionada por Aduvanta Technologies, S.A.P.I. de C.V. ("Aduvanta", "nosotros" o "nuestro"). Al acceder o utilizar el Servicio, usted acepta quedar vinculado por estos Terminos. Si no esta de acuerdo, no podra utilizar el Servicio.',
    sections: [
      {
        heading: '1. Definiciones',
        body: '"Cliente" se refiere a la persona moral o fisica que se registra en el Servicio y celebra un contrato de suscripcion con Aduvanta.\n\n"Organizacion" se refiere al espacio de trabajo (tenant) creado dentro del Servicio, que representa una empresa, agencia aduanal o unidad de negocio.\n\n"Usuario" se refiere a cualquier persona fisica autorizada por el Cliente para acceder al Servicio bajo la Organizacion del Cliente.\n\n"Suscripcion" se refiere al plan de pago seleccionado por el Cliente que determina el nivel de servicio, acceso a funcionalidades y limites de uso.\n\n"Datos del Cliente" se refiere a todos los datos, archivos, documentos, registros e informacion cargados, ingresados o generados por el Cliente o sus Usuarios dentro del Servicio.\n\n"Plataforma" se refiere a la aplicacion web de Aduvanta, sus APIs y toda la infraestructura y servicios relacionados.',
      },
      {
        heading: '2. Registro de Cuenta y Configuracion de Organizacion',
        body: 'Para utilizar el Servicio, debe crear una cuenta y configurar una Organizacion. Usted se compromete a proporcionar informacion veraz, completa y actualizada durante el registro y a mantener actualizada la informacion de su cuenta.\n\nCada Organizacion debe designar al menos un administrador responsable de gestionar Usuarios, roles, permisos y configuraciones de la Organizacion.\n\nUsted es responsable de mantener la confidencialidad de sus credenciales de acceso y de todas las actividades que ocurran bajo su cuenta u Organizacion. Debe notificar a Aduvanta de manera inmediata sobre cualquier uso no autorizado de su cuenta.\n\nAduvanta se reserva el derecho de rechazar registros o suspender cuentas que incumplan estos Terminos o que proporcionen informacion falsa o enganosa.',
      },
      {
        heading: '3. Suscripcion y Facturacion',
        body: 'El Servicio se ofrece mediante suscripcion. Todos los precios se cotizan y son pagaderos en Pesos Mexicanos (MXN) mas los impuestos aplicables (IVA).\n\nLos nuevos Clientes tienen derecho a un periodo de prueba gratuito de 14 dias con acceso completo a las funcionalidades del plan seleccionado. No se requiere informacion de pago para iniciar el periodo de prueba. Al finalizar el periodo de prueba, el Cliente debera seleccionar un plan de pago para continuar utilizando el Servicio.\n\nLas suscripciones se facturan de forma mensual o anual, segun la seleccion del Cliente. Las suscripciones anuales reciben un descuento conforme se publica en nuestra pagina de precios. El pago se debe realizar al inicio de cada ciclo de facturacion.\n\nAduvanta emitira un CFDI (Comprobante Fiscal Digital por Internet) valido por cada pago recibido.\n\nSi el pago no se recibe dentro de los 15 dias naturales posteriores a la fecha de vencimiento, Aduvanta se reserva el derecho de suspender el acceso al Servicio hasta que se reciba el pago. Los incumplimientos de pago reiterados podran resultar en la terminacion de la cuenta.\n\nAduvanta podra ajustar los precios con un aviso previo por escrito de al menos 30 dias. Los cambios de precio entraran en vigor al inicio del siguiente ciclo de facturacion.',
      },
      {
        heading: '4. Uso Aceptable',
        body: 'Usted se compromete a utilizar el Servicio unicamente para fines licitos y de conformidad con estos Terminos. Queda prohibido:\n\n• Utilizar el Servicio para violar cualquier ley o regulacion aplicable, incluyendo las leyes aduaneras, fiscales y de comercio exterior de Mexico.\n• Intentar obtener acceso no autorizado a cualquier parte del Servicio, otras cuentas o sistemas conectados al Servicio.\n• Interferir con o interrumpir la integridad o el rendimiento del Servicio o su infraestructura.\n• Realizar ingenieria inversa, descompilar, desensamblar o intentar obtener el codigo fuente del Servicio.\n• Utilizar el Servicio para transmitir malware, virus o cualquier codigo danino.\n• Compartir credenciales de acceso o permitir que terceros no autorizados accedan al Servicio a traves de su cuenta.\n• Utilizar herramientas automatizadas (bots, scrapers) para acceder al Servicio sin autorizacion previa por escrito de Aduvanta.\n• Cargar o transmitir contenido que infrinja derechos de propiedad intelectual de terceros.\n\nAduvanta se reserva el derecho de suspender o dar por terminado el acceso de cualquier Cliente o Usuario que incumpla estas disposiciones de uso aceptable.',
      },
      {
        heading: '5. Propiedad de los Datos del Cliente',
        body: 'El Cliente conserva todos los derechos de propiedad sobre los Datos del Cliente. Aduvanta no adquiere ningun derecho de propiedad sobre los Datos del Cliente por el hecho de proporcionar el Servicio.\n\nAduvanta actua como encargado del tratamiento respecto a los Datos del Cliente. Tratamos los Datos del Cliente unicamente en la medida necesaria para proporcionar el Servicio y conforme a las instrucciones del Cliente, en cumplimiento con nuestro Aviso de Privacidad y las leyes de proteccion de datos aplicables.\n\nAduvanta no accedera, usara ni divulgara los Datos del Cliente salvo: (a) cuando sea necesario para proporcionar y mantener el Servicio; (b) para cumplir con la ley aplicable o una orden judicial valida; (c) cuando el Cliente lo autorice expresamente; o (d) para proteger la seguridad e integridad del Servicio.\n\nAl terminar la suscripcion, el Cliente podra solicitar la exportacion de sus Datos del Cliente dentro de los 30 dias naturales siguientes. Transcurrido este plazo, Aduvanta podra eliminar permanentemente los Datos del Cliente, salvo cuando la conservacion sea requerida por ley.',
      },
      {
        heading: '6. Propiedad Intelectual',
        body: 'El Servicio, incluyendo su software, arquitectura, diseno, interfaz de usuario, documentacion, APIs, marcas registradas y toda la propiedad intelectual relacionada, es y permanece como propiedad exclusiva de Aduvanta Technologies, S.A.P.I. de C.V.\n\nEstos Terminos otorgan al Cliente una licencia limitada, no exclusiva, intransferible y revocable para acceder y utilizar el Servicio durante el periodo de suscripcion activa, unicamente para las operaciones internas del negocio del Cliente.\n\nNo se otorgan derechos para copiar, modificar, distribuir, vender o crear obras derivadas basadas en el Servicio o cualquier parte del mismo.\n\nLas sugerencias, comentarios o solicitudes de funcionalidades presentadas por los Clientes o Usuarios podran ser utilizadas por Aduvanta sin obligacion alguna de compensacion o atribucion.',
      },
      {
        heading: '7. Disponibilidad del Servicio y SLA',
        body: 'Aduvanta se compromete a una disponibilidad objetivo del 99.9% para el Servicio, medida mensualmente, excluyendo ventanas de mantenimiento programado.\n\nEl mantenimiento programado sera comunicado con al menos 48 horas de anticipacion y se realizara durante periodos de bajo uso siempre que sea posible.\n\nEn caso de que el tiempo de inactividad no programado exceda el objetivo del 99.9% en un mes calendario determinado, los Clientes con planes anuales podran solicitar creditos de servicio conforme al Acuerdo de Nivel de Servicio (SLA) aplicable publicado en nuestro sitio web.\n\nAduvanta no es responsable por tiempo de inactividad causado por: (a) factores fuera de nuestro control razonable, incluyendo eventos de fuerza mayor; (b) equipos, software o conexiones de red del Cliente; (c) servicios o APIs de terceros no operados por Aduvanta; o (d) acciones del Cliente que incumplan estos Terminos.',
      },
      {
        heading: '8. Limitacion de Responsabilidad',
        body: 'En la maxima medida permitida por la ley aplicable:\n\nAduvanta no sera responsable por danos indirectos, incidentales, especiales, consecuentes o punitivos, incluyendo pero sin limitarse a la perdida de utilidades, ingresos, datos, oportunidades de negocio o credito mercantil, que surjan de o en relacion con el uso o la imposibilidad de uso del Servicio.\n\nLa responsabilidad total acumulada de Aduvanta por cualquier reclamacion derivada de o relacionada con estos Terminos o el Servicio no excedera el monto total pagado por el Cliente a Aduvanta durante el periodo de 12 meses inmediatamente anterior al evento que dio origen a la reclamacion.\n\nEl Servicio se proporciona como herramienta de apoyo operativo. Aduvanta no garantiza que el uso del Servicio asegure el cumplimiento de requisitos regulatorios. El Cliente es el unico responsable de verificar la exactitud de las declaraciones aduaneras, clasificaciones arancelarias y todos los tramites regulatorios.\n\nEstas limitaciones aplican independientemente de la teoria legal sobre la cual se base la reclamacion, ya sea contractual, extracontractual, por negligencia, responsabilidad objetiva o de cualquier otra naturaleza.',
      },
      {
        heading: '9. Terminacion',
        body: 'El Cliente podra dar por terminada la suscripcion en cualquier momento mediante aviso por escrito a traves de la plataforma o por correo electronico a legal@aduvanta.com. La terminacion surtira efectos al final del ciclo de facturacion vigente. No se emitiran reembolsos por periodos de facturacion parciales.\n\nAduvanta podra dar por terminado o suspender el acceso del Cliente al Servicio de forma inmediata, sin previo aviso, si: (a) el Cliente incumple materialmente estos Terminos y no subsana el incumplimiento dentro de los 15 dias naturales siguientes a la notificacion por escrito; (b) el Cliente realiza actividades ilegales utilizando el Servicio; (c) el Cliente no realiza el pago de las cuotas por mas de 30 dias naturales despues de su vencimiento; o (d) Aduvanta esta obligado a hacerlo por disposicion legal.\n\nAl momento de la terminacion: (a) todos los derechos otorgados al Cliente bajo estos Terminos cesaran de manera inmediata; (b) el Cliente debera cesar todo uso del Servicio; (c) el Cliente podra solicitar la exportacion de datos dentro de los 30 dias naturales conforme a lo descrito en la Seccion 5; y (d) las obligaciones de pago pendientes subsistiran a la terminacion.',
      },
      {
        heading: '10. Ley Aplicable y Jurisdiccion',
        body: 'Los presentes Terminos se regiran e interpretaran de conformidad con las leyes de los Estados Unidos Mexicanos.\n\nCualquier controversia, disputa o reclamacion que surja de o en relacion con estos Terminos o el Servicio sera sometida a la jurisdiccion exclusiva de los tribunales competentes ubicados en Monterrey, Nuevo Leon, Mexico.\n\nLas partes renuncian a cualquier otra jurisdiccion que pudiera corresponderles por razon de su domicilio presente o futuro o por cualquier otra causa.',
      },
      {
        heading: '11. Disposiciones Generales',
        body: 'Acuerdo completo: Estos Terminos, junto con el Aviso de Privacidad y cualquier Acuerdo de Nivel de Servicio aplicable, constituyen el acuerdo completo entre el Cliente y Aduvanta respecto al Servicio.\n\nDivisibilidad: Si alguna disposicion de estos Terminos se considera invalida o inaplicable, las disposiciones restantes continuaran en pleno vigor y efecto.\n\nRenuncia: La falta de Aduvanta de hacer valer cualquier derecho o disposicion de estos Terminos no constituira una renuncia a dicho derecho o disposicion.\n\nCesion: El Cliente no podra ceder ni transferir estos Terminos sin el consentimiento previo por escrito de Aduvanta. Aduvanta podra ceder estos Terminos en relacion con una fusion, adquisicion o venta de la totalidad o sustancialmente la totalidad de sus activos.\n\nNotificaciones: Las notificaciones de Aduvanta al Cliente se enviaran a la direccion de correo electronico asociada con la cuenta del Cliente. Las notificaciones del Cliente a Aduvanta deberan enviarse a legal@aduvanta.com.',
      },
      {
        heading: '12. Informacion de Contacto',
        body: 'Para preguntas sobre estos Terminos y Condiciones, contactenos en:\n\nAduvanta Technologies, S.A.P.I. de C.V.\nCorreo electronico: legal@aduvanta.com\nSitio web: https://aduvanta.com',
      },
    ],
  },
} as const

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  const isEs = locale === 'es-MX'
  return buildPageMetadata({
    locale,
    title: isEs ? 'Terminos y Condiciones' : 'Terms of Service',
    description: isEs
      ? 'Terminos y Condiciones de Aduvanta. Conoce las condiciones de uso de nuestra plataforma de software aduanal y comercio exterior.'
      : 'Aduvanta Terms of Service. Review the conditions governing the use of our customs and foreign trade software platform.',
    path: '/terminos',
  })
}

export default async function TerminosPage({ params }: Props) {
  const { locale } = await params
  const t = locale === 'es-MX' ? content['es-MX'] : content['en-US']
  const breadcrumb = buildBreadcrumbJsonLd([
    { name: 'Aduvanta', url: `${BASE_URL}/${locale}` },
    { name: t.title, url: `${BASE_URL}/${locale}/terminos` },
  ])

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }}
      />
      <section className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
          {t.title}
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">{t.lastUpdated}</p>
        <p className="mt-6 leading-relaxed text-muted-foreground">{t.intro}</p>

        {t.sections.map((section) => (
          <div key={section.heading} className="mt-10">
            <h2 className="text-xl font-semibold">{section.heading}</h2>
            <div className="mt-3 space-y-4 leading-relaxed text-muted-foreground">
              {section.body.split('\n\n').map((paragraph, i) => (
                <p key={i} className="whitespace-pre-line">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>
        ))}

        <div className="mt-16 border-t pt-8">
          <p className="text-sm text-muted-foreground">
            {locale === 'es-MX' ? (
              <>
                Tambien puedes consultar nuestro{' '}
                <Link
                  href="/privacidad"
                  className="underline hover:text-foreground"
                >
                  Aviso de Privacidad
                </Link>
                .
              </>
            ) : (
              <>
                You may also review our{' '}
                <Link
                  href="/privacidad"
                  className="underline hover:text-foreground"
                >
                  Privacy Policy
                </Link>
                .
              </>
            )}
          </p>
        </div>
      </section>
    </>
  )
}
